language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: FcntBul8Xmgr48KJbJp2sxIsLB3OQJfAyyoHA7y09yyGz9YN55oVdU0XSrENR5ZWgJlGrlXRZIRyl345EQouypnS+iwP3Jhc16VtWzCSKMFMQt430LJmEMYqFH3P3oKo6vyYqem3DZJoezYLq3uQef35PXBSRUy8xBYWdIqnBbA=
  - secure: KDvKpnG0srvSlUSiquOaYvBJLgnzLfJbIhyWSTUy4WwvNQ1HvGlognsNlWa1Z+wqXB9MjSnUrFWDIVKcDqwoUddVhVtqHArZ2kM9gqgBRnT+kSz5rEnp+nj8iynMqtmP6tHBzSmoxBm02+fWBlvkv84NMBWBkWy2yA5BMCV0vT0=
  - secure: NK0qS89MwK+F5aPxyczZrB5WXif07seWIE3e3RraZP43Eu6AbBnlO720ZdHiy2zMZNzTi+CVTNFmQrIC56m0EOK2HksvVPtDjw+11D1Xhjcx6Z1cTCmqnzwobvYdfDVYQjaQYzF3iSgU39zeuPVitkvl1R6oDG/eJYbgyUEPG8Q=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace psq --generator
  "${CMAKE_GENERATOR}" --block "smspillaz/cmake-imported-project"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package="cmake-imported-project"
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/cmake-imported-project
    branch: master
    condition: "${DEPLOY} = 1"
