language: cpp
sudo: false
cache:
  directories:
  - container
env:
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/bii/setup.py -e bash -p /dev/stdout --cmake-version
  ${CMAKE_VERSION})
script:
- polysquare_run check/bii/check.py ${COVERAGE} --cmake-namespace psq --generator
  "${CMAKE_GENERATOR}" --block "smspillaz/cmake-imported-project"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/bii/coverage.py
before_deploy:
- polysquare_run deploy/bii/deploy.py
deploy:
  provider: biicode
  skip_cleanup: true
  user:
    secure: d1EhNwc9kFzwjTNglz8sHKtA4rAHDv48PIpooR8zq3DX7CyqXrGuowT7dv9QF1xp/wg4vAvyxjwVqkmbouwU5yHs0TrxA9nKSTaXmUiKsargzfAbY5gilymaqxcdMGHMYpYtbqLopDuCWec2tQiEdWYG3oxiptqmpRkyj7ZhwAY=
  password:
    secure: Cv5tgXwjXVGRzk2jIWT/ofPEuONNJtjYSeOTqgPF/c0ZK5zBe1jNstgMu9L/SQPBhDVPdShiIOlJkxIdGrhjrArFHwdzkcuAsELtw2oPCi+9AhudxWR54Zjt9M+48QQjvz06JutI1KGRrP7D34zUQMPI3dgvE20omEG28g83d3M=
  on:
    repo: polysquare/cmake-imported-project
    branch: master
    condition: ${DEPLOY} = 1
